/* eslint-disable @typescript-eslint/no-explicit-any */
import type { BadgeVariant } from "@/components/common/badge";
import { linkOptions } from "@tanstack/react-router";

export const SIDEBAR_LINKS = linkOptions([
  {
    title: "لوحة التحكم",
    to: "/dashboard",

    includeChildren: false,
  },
  {
    title: "المخطوطات",
    to: "/dashboard/manuscrits",
    includeChildren: true,
  },
  {
    title: "الخزانات",
    to: "/dashboard/khizanat",
    includeChildren: true,
  },
  {
    title: "الأرشيفات",
    to: "/dashboard/archives",
    includeChildren: true,
  },

  {
    title: "التقارير",
    to: "/dashboard/reports",
    includeChildren: true,
  },
  {
    title: "المستخدمون",
    to: "/dashboard/users",
    includeChildren: true,
  },
]);

export const STEPS = [
  {
    id: "1",
    to: "step-one",
    title: "الفهرسة",
    worker: "موظف الفهرسة",
  },

  {
    id: "2",
    to: "step-two",
    title: "الرقمنة",
    worker: "مشغّل الرقمنة",
  },

  {
    id: "3",
    to: "step-three",
    title: "المراجعة العلمية",
    worker: "المراجع العلمي",
  },

  {
    id: "4",
    to: "step-four",
    title: "المراجعة اللغوية",
    worker: "المُدقِّق العلمي",
  },

  {
    id: "5",
    to: "step-five",
    title: " المعالجة",
    worker: "مسؤول  المعالجة",
  },

  {
    id: "6",
    to: "step-six",
    title: "النشر",
    worker: "مسؤول النشر",
  },
];

type ComboBoxType = {
  label: string;
  value: string;
  variant?: BadgeVariant;
};

export const userRoles: ComboBoxType[] = [
  { value: "khizana_admin", label: "مسؤول خزانة", variant: "secondary" },
  { value: "cataloger", label: "الفهرسة", variant: "success" },
  { value: "digitizer", label: "مكلف بالرقمنة", variant: "warning" },
  { value: "image_processor", label: "مكلف بمعالجة الصور", variant: "danger" },
];

export type TaskStatus = "قيد التنفيذ" | "معلق" | "مكتمل" | "مرفوض";

export const ManuscriptStatus: ComboBoxType[] = [
  { label: "معلق", value: "معلق" },
  { label: "قيد التنفيذ", value: "قيد التنفيذ" },
  { label: "مكتمل", value: "مكتمل" },
  { label: "مرفوض", value: "مرفوض" },
];

export const khizanat: ComboBoxType[] = [
  { label: "خزانة المسجد الأعظم بوزان", value: "01" },
  { label: "خزانة المسجد الأعظم بتازة", value: "02" },
  { label: "خزانة المسجد الأعظم بآسفي", value: "03" },
  { label: "خزانة ابن يوسف بمراكش", value: "04" },
  { label: "خزانة ابن يوسف بمراكش", value: "05" },
  { label: "خزانة القرويين بفاس", value: "06" },
  { label: "خزانة القايد العيادي بابن جرير", value: "07" },
  { label: "خزانة مسجد القصبة بالصويرة", value: "08" },
  { label: "خزانة مولاي ادريس زرهون", value: "09" },
  { label: "خزانة الزاوية الحمزية العياشية بميدلت", value: "10" },
  { label: "خزانة المسجد الأعظم بمكناس", value: "11" },
  { label: "خزانة الزاوية الناصرية بتمكروت", value: "12" },
  { label: "خزانة المسجد الأعظم بسلا", value: "13" },
];

export const users = [
  {
    id: 1,
    name: "أحمد الوزاني",
    email: "ahmad.ouazzani@habous.ma",
    password: "123456",
    role: "khizana_admin",
    khizana: "01",
    isActive: true,
  },
  {
    id: 2,
    name: "فاطمة التازية",
    email: "fatima.taza@habous.ma",
    password: "123456",
    role: "cataloger",
    khizana: "02",
    isActive: true,
  },
  {
    id: 3,
    name: "يوسف المراكشي",
    email: "youssef.marrakech@habous.ma",
    password: "123456",
    role: "digitizer",
    khizana: "04",
    isActive: true,
  },
  {
    id: 4,
    name: "مريم الفاسية",
    email: "meryem.fes@habous.ma",
    password: "123456",
    role: "image_processor",
    khizana: "06",
    isActive: true,
  },
  {
    id: 5,
    name: "عبدالله المكناسي",
    email: "abdellah.meknes@habous.ma",
    password: "123456",
    role: "khizana_admin",
    khizana: "11",
    isActive: false,
  },
  {
    id: 6,
    name: "سلمى السلاوية",
    email: "salma.sale@habous.ma",
    password: "123456",
    role: "cataloger",
    khizana: "13",
    isActive: true,
  },
  {
    id: 7,
    name: "حمزة الميدلتي",
    email: "hamza.midelt@habous.ma",
    password: "123456",
    role: "digitizer",
    khizana: "10",
    isActive: true,
  },
  {
    id: 8,
    name: "ليلى الصويرية",
    email: "leila.essaouira@habous.ma",
    password: "123456",
    role: "image_processor",
    khizana: "08",
    isActive: true,
  },
  {
    id: 9,
    name: "حسن الزرهوني",
    email: "hassan.zarhoun@habous.ma",
    password: "123456",
    role: "cataloger",
    khizana: "09",
    isActive: true,
  },
  {
    id: 10,
    name: "عائشة الميدلتية",
    email: "aicha.midelt@habous.ma",
    password: "123456",
    role: "digitizer",
    khizana: "10",
    isActive: false,
  },
  {
    id: 11,
    name: "مصطفى المكناسي",
    email: "mustapha.meknes@habous.ma",
    password: "123456",
    role: "image_processor",
    khizana: "11",
    isActive: true,
  },
  {
    id: 12,
    name: "خديجة التمكروطية",
    email: "khadija.tamkroute@habous.ma",
    password: "123456",
    role: "khizana_admin",
    khizana: "12",
    isActive: true,
  },
  {
    id: 13,
    name: "نور الدين السلاوي",
    email: "nour.sale@habous.ma",
    password: "123456",
    role: "cataloger",
    khizana: "13",
    isActive: false,
  },
  {
    id: 14,
    name: "جميلة الفاسية",
    email: "jamila.fes@habous.ma",
    password: "123456",
    role: "digitizer",
    khizana: "06",
    isActive: true,
  },
  {
    id: 15,
    name: "عبدالرحيم الوزاني",
    email: "abderrahim.ouazzan@habous.ma",
    password: "123456",
    role: "image_processor",
    khizana: "01",
    isActive: true,
  },
  {
    id: 16,
    name: "سعاد التازية",
    email: "souad.taza@habous.ma",
    password: "123456",
    role: "khizana_admin",
    khizana: "02",
    isActive: false,
  },
  {
    id: 17,
    name: "رشيد المراكشي",
    email: "rachid.marrakech@habous.ma",
    password: "123456",
    role: "cataloger",
    khizana: "04",
    isActive: true,
  },
  {
    id: 18,
    name: "هدى الصويرية",
    email: "houda.essaouira@habous.ma",
    password: "123456",
    role: "digitizer",
    khizana: "08",
    isActive: true,
  },
  {
    id: 19,
    name: "عبدالعزيز الميدلتي",
    email: "abdelaziz.midelt@habous.ma",
    password: "123456",
    role: "image_processor",
    khizana: "10",
    isActive: false,
  },
  {
    id: 20,
    name: "فؤاد الناصري",
    email: "fouad.tamkroute@habous.ma",
    password: "123456",
    role: "khizana_admin",
    khizana: "12",
    isActive: true,
  },
  {
    id: 21,
    name: "ليلى السلاوية",
    email: "layla.sale@habous.ma",
    password: "123456",
    role: "cataloger",
    khizana: "13",
    isActive: true,
  },
  {
    id: 22,
    name: "مروان الفاسي",
    email: "marouane.fes@habous.ma",
    password: "123456",
    role: "digitizer",
    khizana: "06",
    isActive: false,
  },
  {
    id: 23,
    name: "سامي الوزاني",
    email: "sami.ouazzan@habous.ma",
    password: "123456",
    role: "image_processor",
    khizana: "01",
    isActive: true,
  },
  {
    id: 24,
    name: "أسماء التازية",
    email: "asma.taza@habous.ma",
    password: "123456",
    role: "khizana_admin",
    khizana: "02",
    isActive: true,
  },
  {
    id: 25,
    name: "يونس المراكشي",
    email: "younes.marrakech@habous.ma",
    password: "123456",
    role: "cataloger",
    khizana: "05",
    isActive: false,
  },
  {
    id: 26,
    name: "صفاء الصويرية",
    email: "safaa.essaouira@habous.ma",
    password: "123456",
    role: "digitizer",
    khizana: "08",
    isActive: true,
  },
  {
    id: 27,
    name: "عبدالمجيد الميدلتي",
    email: "abdelmajid.midelt@habous.ma",
    password: "123456",
    role: "image_processor",
    khizana: "10",
    isActive: true,
  },
  {
    id: 28,
    name: "رجاء الناصرية",
    email: "rajaa.tamkroute@habous.ma",
    password: "123456",
    role: "khizana_admin",
    khizana: "12",
    isActive: false,
  },
  {
    id: 29,
    name: "طارق السلاوي",
    email: "tarik.sale@habous.ma",
    password: "123456",
    role: "cataloger",
    khizana: "13",
    isActive: true,
  },
  {
    id: 30,
    name: "لمياء الفاسية",
    email: "lamiya.fes@habous.ma",
    password: "123456",
    role: "digitizer",
    khizana: "06",
    isActive: true,
  },
  {
    id: 31,
    name: "عبدالاله الوزاني",
    email: "abdelilah.ouazzan@habous.ma",
    password: "123456",
    role: "image_processor",
    khizana: "01",
    isActive: false,
  },
  {
    id: 32,
    name: "سناء التازية",
    email: "sanaa.taza@habous.ma",
    password: "123456",
    role: "khizana_admin",
    khizana: "02",
    isActive: true,
  },
  {
    id: 33,
    name: "حميد المراكشي",
    email: "hamid.marrakech@habous.ma",
    password: "123456",
    role: "cataloger",
    khizana: "04",
    isActive: true,
  },
  {
    id: 34,
    name: "إيمان الصويرية",
    email: "iman.essaouira@habous.ma",
    password: "123456",
    role: "digitizer",
    khizana: "08",
    isActive: false,
  },
  {
    id: 35,
    name: "عبدالواحد الميدلتي",
    email: "abdelwahid.midelt@habous.ma",
    password: "123456",
    role: "image_processor",
    khizana: "10",
    isActive: true,
  },
  {
    id: 36,
    name: "فاطمة الناصرية",
    email: "fatima.tamkroute@habous.ma",
    password: "123456",
    role: "khizana_admin",
    khizana: "12",
    isActive: true,
  },
  {
    id: 37,
    name: "يوسف السلاوي",
    email: "youssef.sale@habous.ma",
    password: "123456",
    role: "cataloger",
    khizana: "13",
    isActive: false,
  },
  {
    id: 38,
    name: "مريم الفاسية",
    email: "meryem2.fes@habous.ma",
    password: "123456",
    role: "digitizer",
    khizana: "06",
    isActive: true,
  },
  {
    id: 39,
    name: "عبدالرحمان الوزاني",
    email: "abderrahman.ouazzan@habous.ma",
    password: "123456",
    role: "image_processor",
    khizana: "01",
    isActive: true,
  },
];

export const MANUSCRIPTS = [
  {
    id: "MS-2026-001",
    title: "كتاب الحكمة و الفلسفة",
    author: "ابن رشد",
    scribe: null,
    storageLocation: "06",
    releaseDate: "01-01-2000",
    stepStatus: "قيد التنفيذ",
    fontType: "عربي مغربي",
    currentStep: 3,
    material: "ورق",
    linesPerPage: 29,
    dimensions: "20/30",
    classification: "الفلسفة",
    firstDigitalizationDate: "02-12-2026",
    lastDigitalizationDate: "02-12-2026",
    CreationDate: "15-01-2026",
    manuscriptStatus: "جيدة",
    startsWith:
      "الحمد لله الذي ألهمنا حقائق المعاني ودقائق البيان وخصنا ببدائع الأيادي .",
    endsWith:
      "فالحمد لله على التوفيق، ومنه الهداية إلى سواء الطريق، والصلاة والسلام على محمد ذوي (كذا) النفوس الزكية وشرف وكرم ...",
    needToBeMaintenance: false,
    isCurrentlyMaintaning: false,
    maintananceFinished: false,
    numPages: 145,
    language: "العربية",
    cover: "/covers/ms-2026-001.jpg",
    link: "https://manuscripts.gov.ma/view/MS-2026-001",
    century: "القرن الثاني عشر",
    visibility: "private",
    reviewing: {
      stepOne: [
        {
          title: "اكمال الفحص المادي",
          isChecked: true,
        },
        {
          title: "التقطت الصور الأولية",
          isChecked: true,
        },
        {
          title: "توثيق الحالة",
          isChecked: true,
        },
        {
          title: "تحديث نظام الجرد",
          isChecked: true,
        },
      ],
      StepThree: [
        {
          title: "انطباق الصفحة الأولى و الأخيرة مع PDF",
          isChecked: true,
        },
        {
          title: "النص واضح و مقروء",
          isChecked: true,
        },
        {
          title: "المخطوطة كاملة",
          isChecked: true,
        },
      ],
    },
    logs: [
      {
        id: "1",
        title: "تمّت الموافقة على الاستقبال",
        user: {
          name: "أحمد الوزاني",
          role: "مسؤول خزانة",
        },
        date: "2026-02-20T12:47:27.646Z",

        content:
          "تم التحقق من الحالة الفيزيائية للمخطوط. وهو جاهز لعملية الرقمنة.  المخطوطة في حالة جيدة عمومًا، مع وجود تآكل طفيف في التجليد",
      },
      {
        id: "2",
        title: "اكتملت الرقمنة",
        user: {
          name: "أحمد الوزاني",
          role: "مسؤول خزانة",
        },
        date: "2026-02-20T12:47:27.646Z",
        content:
          "تم مسح 145 صفحة بدقة 600 نقطة في البوصة (DPI). جرى التقاط جميع الصفحات بنجاح مع جودة متناسقة ",
      },
      {
        id: "3",
        title: "تمّت الموافقة على المراجعة العلمية",
        user: {
          name: "أحمد الوزاني",
          role: "مسؤول خزانة",
        },
        date: "2026-02-20T12:47:27.646Z",
        content:
          "تم تأكيد أصالة  المخطوطة. وهو نسخة أصلية تعود إلى القرن الثاني عشر. النص واضح وكامل، ويُعد عملًا فلسفيًا مهمًا صالحًا للنشر",
      },
    ],
    pages: [
      {
        id: 1,
        size: "12.4 MB",
        status: "محملة ",
        url: "/covers/ms-2026-001.jpg",
      },
    ],
  },
  {
    id: "MS-2026-002",
    title: "القانون في الطب",
    author: "ابن سينا",
    storageLocation: "04",
    releaseDate: "01-01-1025",
    stepStatus: "قيد التنفيذ",
    fontType: "نسخ",
    currentStep: 5,
    size: 18,
    classification: "الطب",
    firstDigitalizationDate: "02-12-2026",
    lastDigitalizationDate: "02-12-2026",
    manuscriptStatus: "ضعيفة",
    startsWith: "الحمد لله الذي خلق الإنسان...",
    endsWith: "...وهذا آخر القول في الأدوية",
    needToBeMaintenance: true,
    isCurrentlyMaintaning: true,
    maintananceFinished: true,
    latestMaintenance: "02-12-2026",
    numPages: 65,
    language: "العربية",
    cover: "/covers/ms-2026-001.jpg",
    reviewing: {
      stepOne: [
        {
          title: "اكمال الفحص المادي",
          isChecked: true,
        },
        {
          title: "التقطت الصور الأولية",
          isChecked: true,
        },
        {
          title: "توثيق الحالة",
          isChecked: true,
        },
        {
          title: "تحديث نظام الجرد",
          isChecked: true,
        },
      ],
      StepThree: [
        {
          title: "انطباق الصفحة الأولى و الأخيرة مع PDF",
          isChecked: true,
        },
        {
          title: "النص واضح و مقروء",
          isChecked: true,
        },
        {
          title: "المخطوطة كاملة",
          isChecked: true,
        },
      ],
    },
  },
  {
    id: "MS-2026-003",
    title: "رحلة ابن بطوطة",
    author: "ابن بطوطة",
    storageLocation: "01",
    releaseDate: "01-01-1355",
    stepStatus: "معلق",
    fontType: "مغربي مبسوط",
    currentStep: 6,
    size: 20,
    classification: "أدب الرحلات",
    firstDigitalizationDate: "02-12-2026",
    lastDigitalizationDate: "02-12-2026",
    manuscriptStatus: "متوسطة",
    startsWith: "قال الشيخ شمس الدين...",
    endsWith: "...انتهت الرحلة في غرناطة",
    needToBeMaintenance: false,
    isCurrentlyMaintaning: false,
    maintananceFinished: false,
    numPages: 70,
    language: "العربية",
    cover: "/covers/ms-2026-001.jpg",
    reviewing: {
      stepOne: [
        {
          title: "اكمال الفحص المادي",
          isChecked: true,
        },
        {
          title: "التقطت الصور الأولية",
          isChecked: true,
        },
        {
          title: "توثيق الحالة",
          isChecked: true,
        },
        {
          title: "تحديث نظام الجرد",
          isChecked: true,
        },
      ],
      StepThree: [
        {
          title: "انطباق الصفحة الأولى و الأخيرة مع PDF",
          isChecked: true,
        },
        {
          title: "النص واضح و مقروء",
          isChecked: true,
        },
        {
          title: "المخطوطة كاملة",
          isChecked: true,
        },
      ],
    },
  },
  {
    id: "MS-2026-004",
    title: "المقدمة",
    author: "ابن خلدون",
    storageLocation: "06",
    releaseDate: "01-01-1377",
    stepStatus: "مكتمل",
    fontType: "مغربي مجوهر",
    currentStep: 1,
    size: 22,
    classification: "علم الاجتماع",
    firstDigitalizationDate: "02-12-2026",
    lastDigitalizationDate: "02-12-2026",
    manuscriptStatus: "جيدة",
    startsWith: "اعلم أن فن التاريخ...",
    endsWith: "...والله يؤيد بنصره من يشاء",
    needToBeMaintenance: true,
    isCurrentlyMaintaning: true,
    maintananceFinished: false,
    numPages: 206,
    language: "العربية",
    cover: "/covers/ms-2026-001.jpg",
    reviewing: {
      stepOne: [
        {
          title: "اكمال الفحص المادي",
          isChecked: true,
        },
        {
          title: "التقطت الصور الأولية",
          isChecked: true,
        },
        {
          title: "توثيق الحالة",
          isChecked: true,
        },
        {
          title: "تحديث نظام الجرد",
          isChecked: true,
        },
      ],
      StepThree: [
        {
          title: "انطباق الصفحة الأولى و الأخيرة مع PDF",
          isChecked: true,
        },
        {
          title: "النص واضح و مقروء",
          isChecked: true,
        },
        {
          title: "المخطوطة كاملة",
          isChecked: true,
        },
      ],
    },
  },
  {
    id: "MS-2026-005",
    title: "كتاب الشفاء",
    author: "ابن سينا",
    storageLocation: "11",
    releaseDate: "01-01-1020",
    stepStatus: "قيد التنفيذ",
    fontType: "ثلث",
    currentStep: 4,
    size: 16,
    classification: "فلسفة وعلوم",
    firstDigitalizationDate: "02-12-2026",
    lastDigitalizationDate: "02-12-2026",
    manuscriptStatus: "جيدة",
    startsWith: "أما بعد حمد الله...",
    endsWith: "...وهذا تمام المنطق",
    needToBeMaintenance: true,
    isCurrentlyMaintaning: false,
    maintananceFinished: false,
    numPages: 336,
    language: "العربية",
    cover: "/covers/ms-2026-001.jpg",
    reviewing: {
      stepOne: [
        {
          title: "اكمال الفحص المادي",
          isChecked: true,
        },
        {
          title: "التقطت الصور الأولية",
          isChecked: true,
        },
        {
          title: "توثيق الحالة",
          isChecked: true,
        },
        {
          title: "تحديث نظام الجرد",
          isChecked: true,
        },
      ],
      StepThree: [
        {
          title: "انطباق الصفحة الأولى و الأخيرة مع PDF",
          isChecked: true,
        },
        {
          title: "النص واضح و مقروء",
          isChecked: true,
        },
        {
          title: "المخطوطة كاملة",
          isChecked: true,
        },
      ],
    },
  },
  {
    id: "MS-2026-006",
    title: "ديوان المتنبي",
    author: "أبو الطيب المتنبي",
    storageLocation: "12",
    releaseDate: "01-01-0950",
    stepStatus: "معلق",
    fontType: "كوفي",
    currentStep: 6,
    size: 14,
    classification: "الشعر",
    firstDigitalizationDate: "02-12-2026",
    lastDigitalizationDate: "02-12-2026",
    manuscriptStatus: "متوسطة",
    startsWith: "واحر قلباه ممن قلبه شبم...",
    endsWith: "...أنا الذي نظر الأعمى إلى أدبي",
    needToBeMaintenance: true,
    isCurrentlyMaintaning: true,
    maintananceFinished: true,
    numPages: 145,
    language: "العربية",
    cover: "/covers/ms-2026-001.jpg",
    reviewing: {
      stepOne: [
        {
          title: "اكمال الفحص المادي",
          isChecked: true,
        },
        {
          title: "التقطت الصور الأولية",
          isChecked: true,
        },
        {
          title: "توثيق الحالة",
          isChecked: true,
        },
        {
          title: "تحديث نظام الجرد",
          isChecked: true,
        },
      ],
      StepThree: [
        {
          title: "انطباق الصفحة الأولى و الأخيرة مع PDF",
          isChecked: true,
        },
        {
          title: "النص واضح و مقروء",
          isChecked: true,
        },
        {
          title: "المخطوطة كاملة",
          isChecked: true,
        },
      ],
    },
  },
  {
    id: "MS-2026-007",
    title: "البيان والتبيين",
    author: "الجاحظ",
    storageLocation: "13",
    releaseDate: "01-01-0847",
    stepStatus: "قيد التنفيذ",
    fontType: "نسخ",
    currentStep: 2,
    size: 17,
    classification: "الأدب والبلاغة",
    firstDigitalizationDate: "03-12-2026",
    lastDigitalizationDate: "03-12-2026",
    manuscriptStatus: "جيدة",
    startsWith: "هذا كتاب البيان...",
    endsWith: "...تم الجزء الثالث",
    needToBeMaintenance: false,
    isCurrentlyMaintaning: false,
    maintananceFinished: false,
    numPages: 220,
    language: "العربية",
    cover: "/covers/ms-2026-001.jpg",
    reviewing: {
      stepOne: [
        {
          title: "اكمال الفحص المادي",
          isChecked: true,
        },
        {
          title: "التقطت الصور الأولية",
          isChecked: true,
        },
        {
          title: "توثيق الحالة",
          isChecked: true,
        },
        {
          title: "تحديث نظام الجرد",
          isChecked: true,
        },
      ],
      StepThree: [
        {
          title: "انطباق الصفحة الأولى و الأخيرة مع PDF",
          isChecked: true,
        },
        {
          title: "النص واضح و مقروء",
          isChecked: true,
        },
        {
          title: "المخطوطة كاملة",
          isChecked: true,
        },
      ],
    },
  },
  {
    id: "MS-2026-008",
    title: "العقد الفريد",
    author: "ابن عبد ربه",
    storageLocation: "02",
    releaseDate: "01-01-0940",
    stepStatus: "مكتمل",
    fontType: "أندلسي",
    currentStep: 1,
    size: 19,
    classification: "الأدب",
    firstDigitalizationDate: "03-12-2026",
    lastDigitalizationDate: "03-12-2026",
    manuscriptStatus: "متوسطة",
    startsWith: "الحمد لله رب العالمين...",
    endsWith: "...انتهى كتاب الجوهرة",
    needToBeMaintenance: true,
    isCurrentlyMaintaning: true,
    maintananceFinished: true,
    numPages: 310,
    language: "العربية",
    cover: "/covers/ms-2026-001.jpg",
    reviewing: {
      stepOne: [
        {
          title: "اكمال الفحص المادي",
          isChecked: true,
        },
        {
          title: "التقطت الصور الأولية",
          isChecked: true,
        },
        {
          title: "توثيق الحالة",
          isChecked: true,
        },
        {
          title: "تحديث نظام الجرد",
          isChecked: true,
        },
      ],
      StepThree: [
        {
          title: "انطباق الصفحة الأولى و الأخيرة مع PDF",
          isChecked: true,
        },
        {
          title: "النص واضح و مقروء",
          isChecked: true,
        },
        {
          title: "المخطوطة كاملة",
          isChecked: true,
        },
      ],
    },
  },
  {
    id: "MS-2026-009",
    title: "الكامل في التاريخ",
    author: "ابن الأثير",
    storageLocation: "09",
    releaseDate: "01-01-1231",
    stepStatus: "قيد التنفيذ",
    fontType: "نسخ بغدادي",
    currentStep: 6,
    size: 15,
    classification: "التاريخ",
    firstDigitalizationDate: "04-12-2026",
    lastDigitalizationDate: "04-12-2026",
    manuscriptStatus: "ضعيفة",
    startsWith: "ذكر أخبار الأنبياء...",
    endsWith: "...والله الموفق للصواب",
    needToBeMaintenance: true,
    isCurrentlyMaintaning: false,
    maintananceFinished: false,
    numPages: 412,
    language: "العربية",
    cover: "/covers/ms-2026-001.jpg",
    reviewing: {
      stepOne: [
        {
          title: "اكمال الفحص المادي",
          isChecked: true,
        },
        {
          title: "التقطت الصور الأولية",
          isChecked: true,
        },
        {
          title: "توثيق الحالة",
          isChecked: true,
        },
        {
          title: "تحديث نظام الجرد",
          isChecked: true,
        },
      ],
      StepThree: [
        {
          title: "انطباق الصفحة الأولى و الأخيرة مع PDF",
          isChecked: true,
        },
        {
          title: "النص واضح و مقروء",
          isChecked: true,
        },
        {
          title: "المخطوطة كاملة",
          isChecked: true,
        },
      ],
    },
  },
  {
    id: "MS-2026-010",
    title: "الأغاني",
    author: "أبو الفرج الأصفهاني",
    storageLocation: "03",
    releaseDate: "01-01-0967",
    stepStatus: "معلق",
    fontType: "ديواني",
    currentStep: 5,
    size: 18,
    classification: "الفن والأدب",
    firstDigitalizationDate: "04-12-2026",
    lastDigitalizationDate: "04-12-2026",
    manuscriptStatus: "متوسطة",
    startsWith: "هذا خبر الأصوات...",
    endsWith: "...تم كتاب الأغاني بحمد الله",
    needToBeMaintenance: false,
    isCurrentlyMaintaning: false,
    maintananceFinished: false,
    numPages: 520,
    language: "العربية",
    cover: "/covers/ms-2026-001.jpg",
    reviewing: {
      stepOne: [
        {
          title: "اكمال الفحص المادي",
          isChecked: true,
        },
        {
          title: "التقطت الصور الأولية",
          isChecked: true,
        },
        {
          title: "توثيق الحالة",
          isChecked: true,
        },
        {
          title: "تحديث نظام الجرد",
          isChecked: true,
        },
      ],
      StepThree: [
        {
          title: "انطباق الصفحة الأولى و الأخيرة مع PDF",
          isChecked: true,
        },
        {
          title: "النص واضح و مقروء",
          isChecked: true,
        },
        {
          title: "المخطوطة كاملة",
          isChecked: true,
        },
      ],
    },
  },
  {
    id: "MS-2026-011",
    title: "الفهرست",
    author: "ابن النديم",
    storageLocation: "06",
    releaseDate: "01-01-0987",
    stepStatus: "قيد التنفيذ",
    fontType: "نسخ",
    currentStep: 3,
    size: 16,
    classification: "الببليوغرافيا",
    firstDigitalizationDate: "05-12-2026",
    lastDigitalizationDate: "05-12-2026",
    manuscriptStatus: "جيدة",
    startsWith: "هذا فهرست كتب الأمم...",
    endsWith: "...انتهت المقالة العاشرة",
    needToBeMaintenance: false,
    isCurrentlyMaintaning: false,
    maintananceFinished: false,
    numPages: 198,
    language: "العربية",
    cover: "/covers/ms-2026-001.jpg",
    reviewing: {
      stepOne: [
        {
          title: "اكمال الفحص المادي",
          isChecked: true,
        },
        {
          title: "التقطت الصور الأولية",
          isChecked: true,
        },
        {
          title: "توثيق الحالة",
          isChecked: true,
        },
        {
          title: "تحديث نظام الجرد",
          isChecked: true,
        },
      ],
      StepThree: [
        {
          title: "انطباق الصفحة الأولى و الأخيرة مع PDF",
          isChecked: true,
        },
        {
          title: "النص واضح و مقروء",
          isChecked: true,
        },
        {
          title: "المخطوطة كاملة",
          isChecked: true,
        },
      ],
    },
  },
  {
    id: "MS-2026-012",
    title: "المنقذ من الضلال",
    author: "أبو حامد الغزالي",
    storageLocation: "10",
    releaseDate: "01-01-1106",
    stepStatus: "مكتمل",
    fontType: "نسخ قديم",
    currentStep: 1,
    size: 13,
    classification: "التصوف",
    firstDigitalizationDate: "05-12-2026",
    lastDigitalizationDate: "05-12-2026",
    manuscriptStatus: "جيدة",
    startsWith: "الحمد لله الذي بنعمته...",
    endsWith: "...والحمد لله وحده",
    needToBeMaintenance: false,
    isCurrentlyMaintaning: false,
    maintananceFinished: false,
    numPages: 88,
    language: "العربية",
    cover: "/covers/ms-2026-001.jpg",
    reviewing: {
      stepOne: [
        {
          title: "اكمال الفحص المادي",
          isChecked: true,
        },
        {
          title: "التقطت الصور الأولية",
          isChecked: true,
        },
        {
          title: "توثيق الحالة",
          isChecked: true,
        },
        {
          title: "تحديث نظام الجرد",
          isChecked: true,
        },
      ],
      StepThree: [
        {
          title: "انطباق الصفحة الأولى و الأخيرة مع PDF",
          isChecked: true,
        },
        {
          title: "النص واضح و مقروء",
          isChecked: true,
        },
        {
          title: "المخطوطة كاملة",
          isChecked: true,
        },
      ],
    },
  },
  {
    id: "MS-2026-013",
    title: "تاريخ الطبري",
    author: "محمد بن جرير الطبري",
    storageLocation: "07",
    releaseDate: "01-01-0915",
    stepStatus: "قيد التنفيذ",
    fontType: "كوفي قديم",
    currentStep: 4,
    size: 25,
    classification: "التاريخ",
    firstDigitalizationDate: "06-12-2026",
    lastDigitalizationDate: "06-12-2026",
    manuscriptStatus: "ضعيفة",
    startsWith: "القول في زمان الرسل...",
    endsWith: "...في سنة ثلاثمائة للهجرة",
    needToBeMaintenance: true,
    isCurrentlyMaintaning: false,
    maintananceFinished: false,
    numPages: 600,
    language: "العربية",
    cover: "/covers/ms-2026-001.jpg",
    reviewing: {
      stepOne: [
        {
          title: "اكمال الفحص المادي",
          isChecked: true,
        },
        {
          title: "التقطت الصور الأولية",
          isChecked: true,
        },
        {
          title: "توثيق الحالة",
          isChecked: true,
        },
        {
          title: "تحديث نظام الجرد",
          isChecked: true,
        },
      ],
      StepThree: [
        {
          title: "انطباق الصفحة الأولى و الأخيرة مع PDF",
          isChecked: true,
        },
        {
          title: "النص واضح و مقروء",
          isChecked: true,
        },
        {
          title: "المخطوطة كاملة",
          isChecked: true,
        },
      ],
    },
  },
  {
    id: "MS-2026-014",
    title: "إحياء علوم الدين",
    author: "أبو حامد الغزالي",
    storageLocation: "08",
    releaseDate: "01-01-1097",
    stepStatus: "معلق",
    fontType: "نسخ",
    currentStep: 6,
    size: 16,
    classification: "علوم الدين",
    firstDigitalizationDate: "06-12-2026",
    lastDigitalizationDate: "06-12-2026",
    manuscriptStatus: "متوسطة",
    startsWith: "الحمد لله حمداً كثيراً...",
    endsWith: "...وهذا آخر كتاب الموت",
    needToBeMaintenance: false,
    isCurrentlyMaintaning: false,
    maintananceFinished: false,
    numPages: 450,
    language: "العربية",
    cover: "/covers/ms-2026-001.jpg",
    reviewing: {
      stepOne: [
        {
          title: "اكمال الفحص المادي",
          isChecked: true,
        },
        {
          title: "التقطت الصور الأولية",
          isChecked: true,
        },
        {
          title: "توثيق الحالة",
          isChecked: true,
        },
        {
          title: "تحديث نظام الجرد",
          isChecked: true,
        },
      ],
      StepThree: [
        {
          title: "انطباق الصفحة الأولى و الأخيرة مع PDF",
          isChecked: true,
        },
        {
          title: "النص واضح و مقروء",
          isChecked: true,
        },
        {
          title: "المخطوطة كاملة",
          isChecked: true,
        },
      ],
    },
  },
  {
    id: "MS-2026-015",
    title: "الشفاء بالقرآن",
    author: "ابن القيم الجوزية",
    storageLocation: "06",
    releaseDate: "01-01-1340",
    stepStatus: "قيد التنفيذ",
    fontType: "نسخ",
    currentStep: 2,
    size: 15,
    classification: "علوم القرآن",
    firstDigitalizationDate: "07-12-2026",
    lastDigitalizationDate: "07-12-2026",
    manuscriptStatus: "جيدة",
    startsWith: "فصل في هديه صلى الله عليه وسلم...",
    endsWith: "...وهو الشافي لا شفا إلا شفاؤه",
    needToBeMaintenance: false,
    isCurrentlyMaintaning: false,
    maintananceFinished: false,
    numPages: 120,
    language: "العربية",
    cover: "/covers/ms-2026-001.jpg",
    reviewing: {
      stepOne: [
        {
          title: "اكمال الفحص المادي",
          isChecked: true,
        },
        {
          title: "التقطت الصور الأولية",
          isChecked: true,
        },
        {
          title: "توثيق الحالة",
          isChecked: true,
        },
        {
          title: "تحديث نظام الجرد",
          isChecked: true,
        },
      ],
      StepThree: [
        {
          title: "انطباق الصفحة الأولى و الأخيرة مع PDF",
          isChecked: true,
        },
        {
          title: "النص واضح و مقروء",
          isChecked: true,
        },
        {
          title: "المخطوطة كاملة",
          isChecked: true,
        },
      ],
    },
  },
  {
    id: "MS-2026-016",
    title: "مجمع الأمثال",
    author: "الميداني",
    storageLocation: "05",
    releaseDate: "01-01-1124",
    stepStatus: "مكتمل",
    fontType: "فارسي",
    currentStep: 1,
    size: 14,
    classification: "الأدب والأمثال",
    firstDigitalizationDate: "07-12-2026",
    lastDigitalizationDate: "07-12-2026",
    manuscriptStatus: "جيدة",
    startsWith: "الحمد لله الذي زين اللسان...",
    endsWith: "...آخر كتاب الأمثال",
    needToBeMaintenance: false,
    isCurrentlyMaintaning: false,
    maintananceFinished: false,
    numPages: 275,
    language: "العربية",
    cover: "/covers/ms-2026-001.jpg",
    reviewing: {
      stepOne: [
        {
          title: "اكمال الفحص المادي",
          isChecked: true,
        },
        {
          title: "التقطت الصور الأولية",
          isChecked: true,
        },
        {
          title: "توثيق الحالة",
          isChecked: true,
        },
        {
          title: "تحديث نظام الجرد",
          isChecked: true,
        },
      ],
      StepThree: [
        {
          title: "انطباق الصفحة الأولى و الأخيرة مع PDF",
          isChecked: true,
        },
        {
          title: "النص واضح و مقروء",
          isChecked: true,
        },
        {
          title: "المخطوطة كاملة",
          isChecked: true,
        },
      ],
    },
  },
];
