/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as appDashboardRouteRouteImport } from './routes/(app)/dashboard/route'
import { Route as appDashboardIndexRouteImport } from './routes/(app)/dashboard/index'
import { Route as appDashboardUsersIndexRouteImport } from './routes/(app)/dashboard/users/index'
import { Route as appDashboardReportsIndexRouteImport } from './routes/(app)/dashboard/reports/index'
import { Route as appDashboardManuscritsIndexRouteImport } from './routes/(app)/dashboard/manuscrits/index'
import { Route as appDashboardKhizanatIndexRouteImport } from './routes/(app)/dashboard/khizanat/index'
import { Route as appDashboardArchivesIndexRouteImport } from './routes/(app)/dashboard/archives/index'
import { Route as appDashboardstepsStepTwoRouteImport } from './routes/(app)/dashboard/(steps)/step-two'
import { Route as appDashboardstepsStepThreeRouteImport } from './routes/(app)/dashboard/(steps)/step-three'
import { Route as appDashboardstepsStepSixRouteImport } from './routes/(app)/dashboard/(steps)/step-six'
import { Route as appDashboardstepsStepOneRouteImport } from './routes/(app)/dashboard/(steps)/step-one'
import { Route as appDashboardstepsStepFourRouteImport } from './routes/(app)/dashboard/(steps)/step-four'
import { Route as appDashboardstepsStepFiveRouteImport } from './routes/(app)/dashboard/(steps)/step-five'
import { Route as appDashboardManuscritsIdIndexRouteImport } from './routes/(app)/dashboard/manuscrits/$id/index'
import { Route as appDashboardManuscritsIdstepsStepTwoRouteImport } from './routes/(app)/dashboard/manuscrits/$id/(steps)/step-two'
import { Route as appDashboardManuscritsIdstepsStepThreeRouteImport } from './routes/(app)/dashboard/manuscrits/$id/(steps)/step-three'
import { Route as appDashboardManuscritsIdstepsStepSixRouteImport } from './routes/(app)/dashboard/manuscrits/$id/(steps)/step-six'
import { Route as appDashboardManuscritsIdstepsStepOneRouteImport } from './routes/(app)/dashboard/manuscrits/$id/(steps)/step-one'
import { Route as appDashboardManuscritsIdstepsStepFourRouteImport } from './routes/(app)/dashboard/manuscrits/$id/(steps)/step-four'
import { Route as appDashboardManuscritsIdstepsStepFiveRouteImport } from './routes/(app)/dashboard/manuscrits/$id/(steps)/step-five'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const appDashboardRouteRoute = appDashboardRouteRouteImport.update({
  id: '/(app)/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const appDashboardIndexRoute = appDashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => appDashboardRouteRoute,
} as any)
const appDashboardUsersIndexRoute = appDashboardUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => appDashboardRouteRoute,
} as any)
const appDashboardReportsIndexRoute =
  appDashboardReportsIndexRouteImport.update({
    id: '/reports/',
    path: '/reports/',
    getParentRoute: () => appDashboardRouteRoute,
  } as any)
const appDashboardManuscritsIndexRoute =
  appDashboardManuscritsIndexRouteImport.update({
    id: '/manuscrits/',
    path: '/manuscrits/',
    getParentRoute: () => appDashboardRouteRoute,
  } as any)
const appDashboardKhizanatIndexRoute =
  appDashboardKhizanatIndexRouteImport.update({
    id: '/khizanat/',
    path: '/khizanat/',
    getParentRoute: () => appDashboardRouteRoute,
  } as any)
const appDashboardArchivesIndexRoute =
  appDashboardArchivesIndexRouteImport.update({
    id: '/archives/',
    path: '/archives/',
    getParentRoute: () => appDashboardRouteRoute,
  } as any)
const appDashboardstepsStepTwoRoute =
  appDashboardstepsStepTwoRouteImport.update({
    id: '/(steps)/step-two',
    path: '/step-two',
    getParentRoute: () => appDashboardRouteRoute,
  } as any)
const appDashboardstepsStepThreeRoute =
  appDashboardstepsStepThreeRouteImport.update({
    id: '/(steps)/step-three',
    path: '/step-three',
    getParentRoute: () => appDashboardRouteRoute,
  } as any)
const appDashboardstepsStepSixRoute =
  appDashboardstepsStepSixRouteImport.update({
    id: '/(steps)/step-six',
    path: '/step-six',
    getParentRoute: () => appDashboardRouteRoute,
  } as any)
const appDashboardstepsStepOneRoute =
  appDashboardstepsStepOneRouteImport.update({
    id: '/(steps)/step-one',
    path: '/step-one',
    getParentRoute: () => appDashboardRouteRoute,
  } as any)
const appDashboardstepsStepFourRoute =
  appDashboardstepsStepFourRouteImport.update({
    id: '/(steps)/step-four',
    path: '/step-four',
    getParentRoute: () => appDashboardRouteRoute,
  } as any)
const appDashboardstepsStepFiveRoute =
  appDashboardstepsStepFiveRouteImport.update({
    id: '/(steps)/step-five',
    path: '/step-five',
    getParentRoute: () => appDashboardRouteRoute,
  } as any)
const appDashboardManuscritsIdIndexRoute =
  appDashboardManuscritsIdIndexRouteImport.update({
    id: '/manuscrits/$id/',
    path: '/manuscrits/$id/',
    getParentRoute: () => appDashboardRouteRoute,
  } as any)
const appDashboardManuscritsIdstepsStepTwoRoute =
  appDashboardManuscritsIdstepsStepTwoRouteImport.update({
    id: '/manuscrits/$id/(steps)/step-two',
    path: '/manuscrits/$id/step-two',
    getParentRoute: () => appDashboardRouteRoute,
  } as any)
const appDashboardManuscritsIdstepsStepThreeRoute =
  appDashboardManuscritsIdstepsStepThreeRouteImport.update({
    id: '/manuscrits/$id/(steps)/step-three',
    path: '/manuscrits/$id/step-three',
    getParentRoute: () => appDashboardRouteRoute,
  } as any)
const appDashboardManuscritsIdstepsStepSixRoute =
  appDashboardManuscritsIdstepsStepSixRouteImport.update({
    id: '/manuscrits/$id/(steps)/step-six',
    path: '/manuscrits/$id/step-six',
    getParentRoute: () => appDashboardRouteRoute,
  } as any)
const appDashboardManuscritsIdstepsStepOneRoute =
  appDashboardManuscritsIdstepsStepOneRouteImport.update({
    id: '/manuscrits/$id/(steps)/step-one',
    path: '/manuscrits/$id/step-one',
    getParentRoute: () => appDashboardRouteRoute,
  } as any)
const appDashboardManuscritsIdstepsStepFourRoute =
  appDashboardManuscritsIdstepsStepFourRouteImport.update({
    id: '/manuscrits/$id/(steps)/step-four',
    path: '/manuscrits/$id/step-four',
    getParentRoute: () => appDashboardRouteRoute,
  } as any)
const appDashboardManuscritsIdstepsStepFiveRoute =
  appDashboardManuscritsIdstepsStepFiveRouteImport.update({
    id: '/manuscrits/$id/(steps)/step-five',
    path: '/manuscrits/$id/step-five',
    getParentRoute: () => appDashboardRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof appDashboardRouteRouteWithChildren
  '/dashboard/': typeof appDashboardIndexRoute
  '/dashboard/step-five': typeof appDashboardstepsStepFiveRoute
  '/dashboard/step-four': typeof appDashboardstepsStepFourRoute
  '/dashboard/step-one': typeof appDashboardstepsStepOneRoute
  '/dashboard/step-six': typeof appDashboardstepsStepSixRoute
  '/dashboard/step-three': typeof appDashboardstepsStepThreeRoute
  '/dashboard/step-two': typeof appDashboardstepsStepTwoRoute
  '/dashboard/archives/': typeof appDashboardArchivesIndexRoute
  '/dashboard/khizanat/': typeof appDashboardKhizanatIndexRoute
  '/dashboard/manuscrits/': typeof appDashboardManuscritsIndexRoute
  '/dashboard/reports/': typeof appDashboardReportsIndexRoute
  '/dashboard/users/': typeof appDashboardUsersIndexRoute
  '/dashboard/manuscrits/$id/': typeof appDashboardManuscritsIdIndexRoute
  '/dashboard/manuscrits/$id/step-five': typeof appDashboardManuscritsIdstepsStepFiveRoute
  '/dashboard/manuscrits/$id/step-four': typeof appDashboardManuscritsIdstepsStepFourRoute
  '/dashboard/manuscrits/$id/step-one': typeof appDashboardManuscritsIdstepsStepOneRoute
  '/dashboard/manuscrits/$id/step-six': typeof appDashboardManuscritsIdstepsStepSixRoute
  '/dashboard/manuscrits/$id/step-three': typeof appDashboardManuscritsIdstepsStepThreeRoute
  '/dashboard/manuscrits/$id/step-two': typeof appDashboardManuscritsIdstepsStepTwoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof appDashboardIndexRoute
  '/dashboard/step-five': typeof appDashboardstepsStepFiveRoute
  '/dashboard/step-four': typeof appDashboardstepsStepFourRoute
  '/dashboard/step-one': typeof appDashboardstepsStepOneRoute
  '/dashboard/step-six': typeof appDashboardstepsStepSixRoute
  '/dashboard/step-three': typeof appDashboardstepsStepThreeRoute
  '/dashboard/step-two': typeof appDashboardstepsStepTwoRoute
  '/dashboard/archives': typeof appDashboardArchivesIndexRoute
  '/dashboard/khizanat': typeof appDashboardKhizanatIndexRoute
  '/dashboard/manuscrits': typeof appDashboardManuscritsIndexRoute
  '/dashboard/reports': typeof appDashboardReportsIndexRoute
  '/dashboard/users': typeof appDashboardUsersIndexRoute
  '/dashboard/manuscrits/$id': typeof appDashboardManuscritsIdIndexRoute
  '/dashboard/manuscrits/$id/step-five': typeof appDashboardManuscritsIdstepsStepFiveRoute
  '/dashboard/manuscrits/$id/step-four': typeof appDashboardManuscritsIdstepsStepFourRoute
  '/dashboard/manuscrits/$id/step-one': typeof appDashboardManuscritsIdstepsStepOneRoute
  '/dashboard/manuscrits/$id/step-six': typeof appDashboardManuscritsIdstepsStepSixRoute
  '/dashboard/manuscrits/$id/step-three': typeof appDashboardManuscritsIdstepsStepThreeRoute
  '/dashboard/manuscrits/$id/step-two': typeof appDashboardManuscritsIdstepsStepTwoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/(app)/dashboard': typeof appDashboardRouteRouteWithChildren
  '/(app)/dashboard/': typeof appDashboardIndexRoute
  '/(app)/dashboard/(steps)/step-five': typeof appDashboardstepsStepFiveRoute
  '/(app)/dashboard/(steps)/step-four': typeof appDashboardstepsStepFourRoute
  '/(app)/dashboard/(steps)/step-one': typeof appDashboardstepsStepOneRoute
  '/(app)/dashboard/(steps)/step-six': typeof appDashboardstepsStepSixRoute
  '/(app)/dashboard/(steps)/step-three': typeof appDashboardstepsStepThreeRoute
  '/(app)/dashboard/(steps)/step-two': typeof appDashboardstepsStepTwoRoute
  '/(app)/dashboard/archives/': typeof appDashboardArchivesIndexRoute
  '/(app)/dashboard/khizanat/': typeof appDashboardKhizanatIndexRoute
  '/(app)/dashboard/manuscrits/': typeof appDashboardManuscritsIndexRoute
  '/(app)/dashboard/reports/': typeof appDashboardReportsIndexRoute
  '/(app)/dashboard/users/': typeof appDashboardUsersIndexRoute
  '/(app)/dashboard/manuscrits/$id/': typeof appDashboardManuscritsIdIndexRoute
  '/(app)/dashboard/manuscrits/$id/(steps)/step-five': typeof appDashboardManuscritsIdstepsStepFiveRoute
  '/(app)/dashboard/manuscrits/$id/(steps)/step-four': typeof appDashboardManuscritsIdstepsStepFourRoute
  '/(app)/dashboard/manuscrits/$id/(steps)/step-one': typeof appDashboardManuscritsIdstepsStepOneRoute
  '/(app)/dashboard/manuscrits/$id/(steps)/step-six': typeof appDashboardManuscritsIdstepsStepSixRoute
  '/(app)/dashboard/manuscrits/$id/(steps)/step-three': typeof appDashboardManuscritsIdstepsStepThreeRoute
  '/(app)/dashboard/manuscrits/$id/(steps)/step-two': typeof appDashboardManuscritsIdstepsStepTwoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/dashboard/'
    | '/dashboard/step-five'
    | '/dashboard/step-four'
    | '/dashboard/step-one'
    | '/dashboard/step-six'
    | '/dashboard/step-three'
    | '/dashboard/step-two'
    | '/dashboard/archives/'
    | '/dashboard/khizanat/'
    | '/dashboard/manuscrits/'
    | '/dashboard/reports/'
    | '/dashboard/users/'
    | '/dashboard/manuscrits/$id/'
    | '/dashboard/manuscrits/$id/step-five'
    | '/dashboard/manuscrits/$id/step-four'
    | '/dashboard/manuscrits/$id/step-one'
    | '/dashboard/manuscrits/$id/step-six'
    | '/dashboard/manuscrits/$id/step-three'
    | '/dashboard/manuscrits/$id/step-two'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/dashboard/step-five'
    | '/dashboard/step-four'
    | '/dashboard/step-one'
    | '/dashboard/step-six'
    | '/dashboard/step-three'
    | '/dashboard/step-two'
    | '/dashboard/archives'
    | '/dashboard/khizanat'
    | '/dashboard/manuscrits'
    | '/dashboard/reports'
    | '/dashboard/users'
    | '/dashboard/manuscrits/$id'
    | '/dashboard/manuscrits/$id/step-five'
    | '/dashboard/manuscrits/$id/step-four'
    | '/dashboard/manuscrits/$id/step-one'
    | '/dashboard/manuscrits/$id/step-six'
    | '/dashboard/manuscrits/$id/step-three'
    | '/dashboard/manuscrits/$id/step-two'
  id:
    | '__root__'
    | '/'
    | '/(app)/dashboard'
    | '/(app)/dashboard/'
    | '/(app)/dashboard/(steps)/step-five'
    | '/(app)/dashboard/(steps)/step-four'
    | '/(app)/dashboard/(steps)/step-one'
    | '/(app)/dashboard/(steps)/step-six'
    | '/(app)/dashboard/(steps)/step-three'
    | '/(app)/dashboard/(steps)/step-two'
    | '/(app)/dashboard/archives/'
    | '/(app)/dashboard/khizanat/'
    | '/(app)/dashboard/manuscrits/'
    | '/(app)/dashboard/reports/'
    | '/(app)/dashboard/users/'
    | '/(app)/dashboard/manuscrits/$id/'
    | '/(app)/dashboard/manuscrits/$id/(steps)/step-five'
    | '/(app)/dashboard/manuscrits/$id/(steps)/step-four'
    | '/(app)/dashboard/manuscrits/$id/(steps)/step-one'
    | '/(app)/dashboard/manuscrits/$id/(steps)/step-six'
    | '/(app)/dashboard/manuscrits/$id/(steps)/step-three'
    | '/(app)/dashboard/manuscrits/$id/(steps)/step-two'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  appDashboardRouteRoute: typeof appDashboardRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/dashboard': {
      id: '/(app)/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof appDashboardRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/dashboard/': {
      id: '/(app)/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof appDashboardIndexRouteImport
      parentRoute: typeof appDashboardRouteRoute
    }
    '/(app)/dashboard/users/': {
      id: '/(app)/dashboard/users/'
      path: '/users'
      fullPath: '/dashboard/users/'
      preLoaderRoute: typeof appDashboardUsersIndexRouteImport
      parentRoute: typeof appDashboardRouteRoute
    }
    '/(app)/dashboard/reports/': {
      id: '/(app)/dashboard/reports/'
      path: '/reports'
      fullPath: '/dashboard/reports/'
      preLoaderRoute: typeof appDashboardReportsIndexRouteImport
      parentRoute: typeof appDashboardRouteRoute
    }
    '/(app)/dashboard/manuscrits/': {
      id: '/(app)/dashboard/manuscrits/'
      path: '/manuscrits'
      fullPath: '/dashboard/manuscrits/'
      preLoaderRoute: typeof appDashboardManuscritsIndexRouteImport
      parentRoute: typeof appDashboardRouteRoute
    }
    '/(app)/dashboard/khizanat/': {
      id: '/(app)/dashboard/khizanat/'
      path: '/khizanat'
      fullPath: '/dashboard/khizanat/'
      preLoaderRoute: typeof appDashboardKhizanatIndexRouteImport
      parentRoute: typeof appDashboardRouteRoute
    }
    '/(app)/dashboard/archives/': {
      id: '/(app)/dashboard/archives/'
      path: '/archives'
      fullPath: '/dashboard/archives/'
      preLoaderRoute: typeof appDashboardArchivesIndexRouteImport
      parentRoute: typeof appDashboardRouteRoute
    }
    '/(app)/dashboard/(steps)/step-two': {
      id: '/(app)/dashboard/(steps)/step-two'
      path: '/step-two'
      fullPath: '/dashboard/step-two'
      preLoaderRoute: typeof appDashboardstepsStepTwoRouteImport
      parentRoute: typeof appDashboardRouteRoute
    }
    '/(app)/dashboard/(steps)/step-three': {
      id: '/(app)/dashboard/(steps)/step-three'
      path: '/step-three'
      fullPath: '/dashboard/step-three'
      preLoaderRoute: typeof appDashboardstepsStepThreeRouteImport
      parentRoute: typeof appDashboardRouteRoute
    }
    '/(app)/dashboard/(steps)/step-six': {
      id: '/(app)/dashboard/(steps)/step-six'
      path: '/step-six'
      fullPath: '/dashboard/step-six'
      preLoaderRoute: typeof appDashboardstepsStepSixRouteImport
      parentRoute: typeof appDashboardRouteRoute
    }
    '/(app)/dashboard/(steps)/step-one': {
      id: '/(app)/dashboard/(steps)/step-one'
      path: '/step-one'
      fullPath: '/dashboard/step-one'
      preLoaderRoute: typeof appDashboardstepsStepOneRouteImport
      parentRoute: typeof appDashboardRouteRoute
    }
    '/(app)/dashboard/(steps)/step-four': {
      id: '/(app)/dashboard/(steps)/step-four'
      path: '/step-four'
      fullPath: '/dashboard/step-four'
      preLoaderRoute: typeof appDashboardstepsStepFourRouteImport
      parentRoute: typeof appDashboardRouteRoute
    }
    '/(app)/dashboard/(steps)/step-five': {
      id: '/(app)/dashboard/(steps)/step-five'
      path: '/step-five'
      fullPath: '/dashboard/step-five'
      preLoaderRoute: typeof appDashboardstepsStepFiveRouteImport
      parentRoute: typeof appDashboardRouteRoute
    }
    '/(app)/dashboard/manuscrits/$id/': {
      id: '/(app)/dashboard/manuscrits/$id/'
      path: '/manuscrits/$id'
      fullPath: '/dashboard/manuscrits/$id/'
      preLoaderRoute: typeof appDashboardManuscritsIdIndexRouteImport
      parentRoute: typeof appDashboardRouteRoute
    }
    '/(app)/dashboard/manuscrits/$id/(steps)/step-two': {
      id: '/(app)/dashboard/manuscrits/$id/(steps)/step-two'
      path: '/manuscrits/$id/step-two'
      fullPath: '/dashboard/manuscrits/$id/step-two'
      preLoaderRoute: typeof appDashboardManuscritsIdstepsStepTwoRouteImport
      parentRoute: typeof appDashboardRouteRoute
    }
    '/(app)/dashboard/manuscrits/$id/(steps)/step-three': {
      id: '/(app)/dashboard/manuscrits/$id/(steps)/step-three'
      path: '/manuscrits/$id/step-three'
      fullPath: '/dashboard/manuscrits/$id/step-three'
      preLoaderRoute: typeof appDashboardManuscritsIdstepsStepThreeRouteImport
      parentRoute: typeof appDashboardRouteRoute
    }
    '/(app)/dashboard/manuscrits/$id/(steps)/step-six': {
      id: '/(app)/dashboard/manuscrits/$id/(steps)/step-six'
      path: '/manuscrits/$id/step-six'
      fullPath: '/dashboard/manuscrits/$id/step-six'
      preLoaderRoute: typeof appDashboardManuscritsIdstepsStepSixRouteImport
      parentRoute: typeof appDashboardRouteRoute
    }
    '/(app)/dashboard/manuscrits/$id/(steps)/step-one': {
      id: '/(app)/dashboard/manuscrits/$id/(steps)/step-one'
      path: '/manuscrits/$id/step-one'
      fullPath: '/dashboard/manuscrits/$id/step-one'
      preLoaderRoute: typeof appDashboardManuscritsIdstepsStepOneRouteImport
      parentRoute: typeof appDashboardRouteRoute
    }
    '/(app)/dashboard/manuscrits/$id/(steps)/step-four': {
      id: '/(app)/dashboard/manuscrits/$id/(steps)/step-four'
      path: '/manuscrits/$id/step-four'
      fullPath: '/dashboard/manuscrits/$id/step-four'
      preLoaderRoute: typeof appDashboardManuscritsIdstepsStepFourRouteImport
      parentRoute: typeof appDashboardRouteRoute
    }
    '/(app)/dashboard/manuscrits/$id/(steps)/step-five': {
      id: '/(app)/dashboard/manuscrits/$id/(steps)/step-five'
      path: '/manuscrits/$id/step-five'
      fullPath: '/dashboard/manuscrits/$id/step-five'
      preLoaderRoute: typeof appDashboardManuscritsIdstepsStepFiveRouteImport
      parentRoute: typeof appDashboardRouteRoute
    }
  }
}

interface appDashboardRouteRouteChildren {
  appDashboardIndexRoute: typeof appDashboardIndexRoute
  appDashboardstepsStepFiveRoute: typeof appDashboardstepsStepFiveRoute
  appDashboardstepsStepFourRoute: typeof appDashboardstepsStepFourRoute
  appDashboardstepsStepOneRoute: typeof appDashboardstepsStepOneRoute
  appDashboardstepsStepSixRoute: typeof appDashboardstepsStepSixRoute
  appDashboardstepsStepThreeRoute: typeof appDashboardstepsStepThreeRoute
  appDashboardstepsStepTwoRoute: typeof appDashboardstepsStepTwoRoute
  appDashboardArchivesIndexRoute: typeof appDashboardArchivesIndexRoute
  appDashboardKhizanatIndexRoute: typeof appDashboardKhizanatIndexRoute
  appDashboardManuscritsIndexRoute: typeof appDashboardManuscritsIndexRoute
  appDashboardReportsIndexRoute: typeof appDashboardReportsIndexRoute
  appDashboardUsersIndexRoute: typeof appDashboardUsersIndexRoute
  appDashboardManuscritsIdIndexRoute: typeof appDashboardManuscritsIdIndexRoute
  appDashboardManuscritsIdstepsStepFiveRoute: typeof appDashboardManuscritsIdstepsStepFiveRoute
  appDashboardManuscritsIdstepsStepFourRoute: typeof appDashboardManuscritsIdstepsStepFourRoute
  appDashboardManuscritsIdstepsStepOneRoute: typeof appDashboardManuscritsIdstepsStepOneRoute
  appDashboardManuscritsIdstepsStepSixRoute: typeof appDashboardManuscritsIdstepsStepSixRoute
  appDashboardManuscritsIdstepsStepThreeRoute: typeof appDashboardManuscritsIdstepsStepThreeRoute
  appDashboardManuscritsIdstepsStepTwoRoute: typeof appDashboardManuscritsIdstepsStepTwoRoute
}

const appDashboardRouteRouteChildren: appDashboardRouteRouteChildren = {
  appDashboardIndexRoute: appDashboardIndexRoute,
  appDashboardstepsStepFiveRoute: appDashboardstepsStepFiveRoute,
  appDashboardstepsStepFourRoute: appDashboardstepsStepFourRoute,
  appDashboardstepsStepOneRoute: appDashboardstepsStepOneRoute,
  appDashboardstepsStepSixRoute: appDashboardstepsStepSixRoute,
  appDashboardstepsStepThreeRoute: appDashboardstepsStepThreeRoute,
  appDashboardstepsStepTwoRoute: appDashboardstepsStepTwoRoute,
  appDashboardArchivesIndexRoute: appDashboardArchivesIndexRoute,
  appDashboardKhizanatIndexRoute: appDashboardKhizanatIndexRoute,
  appDashboardManuscritsIndexRoute: appDashboardManuscritsIndexRoute,
  appDashboardReportsIndexRoute: appDashboardReportsIndexRoute,
  appDashboardUsersIndexRoute: appDashboardUsersIndexRoute,
  appDashboardManuscritsIdIndexRoute: appDashboardManuscritsIdIndexRoute,
  appDashboardManuscritsIdstepsStepFiveRoute:
    appDashboardManuscritsIdstepsStepFiveRoute,
  appDashboardManuscritsIdstepsStepFourRoute:
    appDashboardManuscritsIdstepsStepFourRoute,
  appDashboardManuscritsIdstepsStepOneRoute:
    appDashboardManuscritsIdstepsStepOneRoute,
  appDashboardManuscritsIdstepsStepSixRoute:
    appDashboardManuscritsIdstepsStepSixRoute,
  appDashboardManuscritsIdstepsStepThreeRoute:
    appDashboardManuscritsIdstepsStepThreeRoute,
  appDashboardManuscritsIdstepsStepTwoRoute:
    appDashboardManuscritsIdstepsStepTwoRoute,
}

const appDashboardRouteRouteWithChildren =
  appDashboardRouteRoute._addFileChildren(appDashboardRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  appDashboardRouteRoute: appDashboardRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
